version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands: 
      - npm --version  
      - pwd
    build:
      commands:
        - mkdir build-output
        - pwd
    post_build:
      commands:
        - mkdir build-input

artifacts:
  files:
    - '**/*'
