parameters:
  pool:["ubuntu-latest","windows-latest"]
# - name: 'pool'
#   type: object
#   default: {"ubuntu-latest","windows-latest"}

jobs:
- job: build
  pool: ${{ parameters.pool }}
  steps:
    - ${{ each project in parameters.pool }}:
      - script: echo My favorite vegetable is ${{ parameters.pool }}